#if DEBUG
import Foundation
let classic1151 = HymnIdentifier(hymnType: .classic, hymnNumber: "1151")
let chinese216 = HymnIdentifier(hymnType: .chineseSupplement, hymnNumber: "216", queryParams: ["gb": "1"])
let classic40 = HymnIdentifier(hymnType: .classic, hymnNumber: "40")
let classic2 = HymnIdentifier(hymnType: .classic, hymnNumber: "2")
let classic3 = HymnIdentifier(hymnType: .classic, hymnNumber: "3")
let classic1151Entity = HymnEntity(hymnIdentifier: classic1151, title: Optional("Hymn: Minoru\'s song"), lyricsJson: Optional("[{\"verse_content\": [\"verse 1 line 1\", \"verse 2 line 2\", \"verse 3 really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really really long line 3\", \"verse 4 line 4\"], \"verse_type\": \"verse\"}, {\"verse_content\": [\"chorus line 1\", \"chorus line 2\", \"chorus line 3\", \"chorus line 4\", \"chorus line 5\", \"chorus line 6\", \"chorus line 7\"], \"verse_type\": \"chorus\"}, {\"verse_content\": [\"verse 3 line 1\", \"verse 3 line 2\", \"verse 3 line 3\", \"verse 3 line 4\"], \"verse_type\": \"verse\"}]"), category: "song's category", subcategory: "song's subcategory", languagesJson: "{\"data\": [{\"path\": \"/en/hymn/cb/1151\", \"value\": \"Cebuano\"}, {\"path\": \"/en/hymn/ts/216?gb=1\", \"value\": \"\u{8bd7}\u{6b4c}(\u{7b80})\"}, {\"path\": \"/en/hymn/ts/216\", \"value\": \"\u{8a69}\u{6b4c}(\u{7e41})\"}, {\"path\": \"/en/hymn/hd/35\", \"value\": \"Dutch\"}, {\"path\": \"/en/hymn/ht/1151\", \"value\": \"Tagalog\"}], \"name\": \"Languages\"}", relevantJson: "{\"data\": [{\"path\": \"/en/hymn/h/2\", \"value\": \"New Tune\"}], \"name\": \"Relevant\"}")
let classic2Entity = HymnEntity(hymnIdentifier: classic2, title: Optional("Classic 2"), lyricsJson: Optional("[{\"verse_content\": [\"classic hymn 2 lyrics\"], \"verse_type\": \"verse\"}]"))
let chinese216Entity = HymnEntity(hymnIdentifier: chinese216, title: Optional("Hymn: Minoru\'s song in Chinese"), lyricsJson: Optional("[{\"verse_content\": [\"chinese verse 1 chinese line 1\"], \"verse_type\": \"verse\"}]"))
#endif
